// Her kategori için en az 50 soru içeren genişletilmiş quiz veri seti
const quizData = {
    "genel-kultur": {
        id: "genel-kultur",
        title: "Genel Kültür",
        icon: "🌍",
        questions: [
            { question: "Türkiye'nin başkenti neresidir?", options: ["İstanbul", "Ankara", "İzmir", "Antalya"], answer: 1 },
            { question: "Hangi hayvan uçabilir?", options: ["Kedi", "Köpek", "Kuş", "İnek"], answer: 2 },
            { question: "Güneş sistemimizde kaç gezegen vardır?", options: ["7", "8", "9", "10"], answer: 1 },
            { question: "Haftada kaç gün vardır?", options: ["5", "6", "7", "8"], answer: 2 },
            { question: "En büyük okyanus hangisidir?", options: ["Atlas Okyanusu", "Hint Okyanusu", "Pasifik Okyanusu", "Kuzey Buz Denizi"], answer: 2 },
            { question: "Türkiye'nin nüfusça en büyük şehri hangisidir?", options: ["İstanbul", "Ankara", "İzmir", "Bursa"], answer: 0 },
            { question: "Türk bayrağının renkleri nelerdir?", options: ["Kırmızı-Beyaz", "Mavi-Beyaz", "Yeşil-Beyaz", "Sarı-Kırmızı"], answer: 0 },
            { question: "Bir yılda kaç ay vardır?", options: ["10", "11", "12", "13"], answer: 2 },
            { question: "Bir günde kaç saat vardır?", options: ["20", "22", "24", "26"], answer: 2 },
            { question: "Dünyamızın uydusu nedir?", options: ["Güneş", "Ay", "Mars", "Venüs"], answer: 1 },
            { question: "Dünyaya en yakın yıldız hangisidir?", options: ["Ay", "Güneş", "Mars", "Jüpiter"], answer: 1 },
            { question: "Hangi mevsimde kar yağar?", options: ["Yaz", "Kış", "İlkbahar", "Sonbahar"], answer: 1 },
            { question: "Türkiye'nin para birimi nedir?", options: ["Dolar", "Euro", "Lira", "Sterlin"], answer: 2 },
            { question: "Cumhuriyet Bayramı hangi tarihte kutlanır?", options: ["23 Nisan", "19 Mayıs", "29 Ekim", "30 Ağustos"], answer: 2 },
            { question: "Ulusal Egemenlik ve Çocuk Bayramı hangi tarihte kutlanır?", options: ["23 Nisan", "19 Mayıs", "29 Ekim", "30 Ağustos"], answer: 0 },
            { question: "Zafer Bayramı hangi tarihte kutlanır?", options: ["23 Nisan", "19 Mayıs", "30 Ağustos", "29 Ekim"], answer: 2 },
            { question: "Atatürk'ü Anma Gençlik ve Spor Bayramı hangi tarihte kutlanır?", options: ["19 Mayıs", "23 Nisan", "30 Ağustos", "29 Ekim"], answer: 0 },
            { question: "Türkiye Cumhuriyeti'nin ilk cumhurbaşkanı kimdir?", options: ["İsmet İnönü", "Mustafa Kemal Atatürk", "Celal Bayar", "Fahrettin Kerim"], answer: 1 },
            { question: "Güneş sistemindeki en küçük gezegen hangisidir?", options: ["Merkür", "Dünya", "Mars", "Jüpiter"], answer: 0 },
            { question: "Güneş sistemindeki en büyük gezegen hangisidir?", options: ["Dünya", "Merkür", "Jüpiter", "Mars"], answer: 2 },
            { question: "Deniz seviyesinde suyun kaynama derecesi kaçtır?", options: ["50", "100", "150", "200"], answer: 1 },
            { question: "Suyun donma derecesi kaçtır?", options: ["0", "10", "-10", "100"], answer: 0 },
            { question: "Dünyanın şekli nasıldır?", options: ["Kare", "Küre", "Üçgen", "Silindir"], answer: 1 },
            { question: "Hangi hayvan denizde yaşar?", options: ["Kedi", "Balina", "Tavşan", "At"], answer: 1 },
            { question: "Hangi hayvan grubu yavrularını sütle besler?", options: ["Memeliler", "Kuşlar", "Balıklar", "Böcekler"], answer: 0 },
            { question: "Kaplumbağa nerede yaşar?", options: ["Sadece denizde", "Sadece karada", "Karada ve suda", "Havada"], answer: 2 },
            { question: "En hızlı kara hayvanı hangisidir?", options: ["Fil", "Çita", "Kaplumbağa", "Koyun"], answer: 1 },
            { question: "Bitkiler büyümek için nelere ihtiyaç duyar?", options: ["Sadece suya", "Sadece güneşe", "Su, güneş ve toprağa", "Hiçbirine"], answer: 2 },
            { question: "İnsan vücudunda kaç duyu organı vardır?", options: ["3", "4", "5", "6"], answer: 2 },
            { question: "Kalbimiz vücudumuzda ne işe yarar?", options: ["Nefes almamızı sağlar", "Kanı pompalar", "Yemek sindirir", "Görmemizi sağlar"], answer: 1 },
            { question: "Akciğerlerimiz ne işe yarar?", options: ["Görmemize", "Duymamıza", "Nefes almamıza", "Yürümemize"], answer: 2 },
            { question: "Türkiye hangi kıtalarda yer alır?", options: ["Sadece Afrika", "Asya ve Avrupa", "Sadece Amerika", "Avustralya"], answer: 1 },
            { question: "Türkiye'nin çevresindeki denizlerden biri hangisidir?", options: ["Kızıldeniz", "Karadeniz", "Hint Okyanusu", "Baltık Denizi"], answer: 1 },
            { question: "İstanbul Boğazı hangi iki denizi birbirine bağlar?", options: ["Karadeniz-Marmara", "Ege-Akdeniz", "Marmara-Ege", "Karadeniz-Akdeniz"], answer: 0 },
            { question: "Dünyanın en uzun nehri hangisidir?", options: ["Nil", "Fırat", "Dicle", "Tuna"], answer: 0 },
            { question: "Gökkuşağında kaç renk vardır?", options: ["5", "6", "7", "8"], answer: 2 },
            { question: "Bir yılda kaç mevsim vardır?", options: ["2", "3", "4", "5"], answer: 2 },
            { question: "Yıldızlar gökyüzünde ne zaman görünür?", options: ["Gündüz", "Gece", "Öğlen", "Sabah"], answer: 1 },
            { question: "Ay'a giden araçlar genellikle ne tür araçlardır?", options: ["Uçak", "Uzay aracı", "Gemi", "Tren"], answer: 1 },
            { question: "Bal arıları hangi maddeyi üretir?", options: ["Süt", "Bal", "Yağ", "Şeker"], answer: 1 },
            { question: "Örümceğin kaç bacağı vardır?", options: ["4", "6", "8", "10"], answer: 2 },
            { question: "Kurbağa hangi hayvan grubuna girer?", options: ["Memeli", "Sürüngen", "Kuş", "Amfibi (iki yaşamlı)"], answer: 3 },
            { question: "Yılan hangi hayvan grubuna girer?", options: ["Memeli", "Kuş", "Sürüngen", "Balık"], answer: 2 },
            { question: "Türkiye'de bir haftanın ilk günü hangisidir?", options: ["Pazar", "Pazartesi", "Cumartesi", "Salı"], answer: 1 },
            { question: "Bir yıl yaklaşık kaç gün sürer?", options: ["300", "365", "400", "500"], answer: 1 },
            { question: "Türkiye'nin komşu ülkelerinden biri hangisidir?", options: ["Fransa", "Yunanistan", "İspanya", "Portekiz"], answer: 1 },
            { question: "Ünlü piramitler hangi ülkede bulunur?", options: ["Türkiye", "Mısır", "Yunanistan", "İtalya"], answer: 1 },
            { question: "Ay, Dünya'nın etrafında ne kadar sürede bir tur atar?", options: ["1 gün", "1 hafta", "Yaklaşık 1 ay", "1 yıl"], answer: 2 },
            { question: "Hangisi bir müzik aletidir?", options: ["Gitar", "Masa", "Kalem", "Sandalye"], answer: 0 },
            { question: "Hangisi bir spor dalıdır?", options: ["Futbol", "Yemek pişirme", "Uyumak", "Okumak"], answer: 0 },
            { question: "Dünyanın en büyük çölü hangisidir?", options: ["Gobi", "Sahra", "Kalahari", "Atacama"], answer: 1 },
            { question: "Everest Dağı dünyanın en yüksek dağıdır, hangi kıtada bulunur?", options: ["Afrika", "Asya", "Avrupa", "Avustralya"], answer: 1 },
            { question: "Çin Seddi hangi ülkededir?", options: ["Japonya", "Çin", "Hindistan", "Moğolistan"], answer: 1 },
            { question: "Kızıl Gezegen olarak bilinen gezegen hangisidir?", options: ["Venüs", "Mars", "Jüpiter", "Satürn"], answer: 1 },
            { question: "Amazon Nehri hangi kıtada akar?", options: ["Afrika", "Asya", "Güney Amerika", "Avrupa"], answer: 2 },
            { question: "Dünyanın en büyük adası hangisidir?", options: ["Avustralya", "Grönland", "Madagaskar", "Borneo"], answer: 1 },
            { question: "Uzaya çıkan ilk insan kimdir?", options: ["Neil Armstrong", "Yuri Gagarin", "Buzz Aldrin", "John Glenn"], answer: 1 },
            { question: "Ay'a ilk ayak basan astronot kimdir?", options: ["Yuri Gagarin", "Neil Armstrong", "Buzz Aldrin", "Michael Collins"], answer: 1 }
        ]
    },
    "matematik": {
        id: "matematik",
        title: "Matematik",
        icon: "🔢",
        questions: [
            { question: "5 + 7 kaçtır?", options: ["10", "11", "12", "13"], answer: 2 },
            { question: "10 - 4 kaçtır?", options: ["4", "5", "6", "7"], answer: 2 },
            { question: "2 x 3 kaçtır?", options: ["5", "6", "8", "9"], answer: 1 },
            { question: "Yarısı 5 olan sayı kaçtır?", options: ["10", "15", "20", "25"], answer: 0 },
            { question: "Hangi şeklin 3 kenarı vardır?", options: ["Kare", "Dikdörtgen", "Üçgen", "Daire"], answer: 2 },
            { question: "8 + 6 kaçtır?", options: ["12", "13", "14", "15"], answer: 2 },
            { question: "9 + 9 kaçtır?", options: ["16", "17", "18", "19"], answer: 2 },
            { question: "15 - 7 kaçtır?", options: ["6", "7", "8", "9"], answer: 2 },
            { question: "20 - 12 kaçtır?", options: ["6", "7", "8", "9"], answer: 2 },
            { question: "4 x 4 kaçtır?", options: ["12", "14", "16", "18"], answer: 2 },
            { question: "5 x 5 kaçtır?", options: ["20", "25", "30", "35"], answer: 1 },
            { question: "6 x 2 kaçtır?", options: ["10", "12", "14", "16"], answer: 1 },
            { question: "12 ÷ 3 kaçtır?", options: ["3", "4", "5", "6"], answer: 1 },
            { question: "10 ÷ 2 kaçtır?", options: ["3", "4", "5", "6"], answer: 2 },
            { question: "100'ün yarısı kaçtır?", options: ["25", "50", "75", "100"], answer: 1 },
            { question: "20'nin iki katı kaçtır?", options: ["30", "35", "40", "45"], answer: 2 },
            { question: "Hangisi çift sayıdır?", options: ["3", "5", "8", "7"], answer: 2 },
            { question: "Hangisi tek sayıdır?", options: ["4", "6", "9", "10"], answer: 2 },
            { question: "100 sayısından önce gelen sayı kaçtır?", options: ["98", "99", "101", "102"], answer: 1 },
            { question: "50 sayısından sonra gelen sayı kaçtır?", options: ["49", "51", "52", "60"], answer: 1 },
            { question: "Hangisi en büyük sayıdır?", options: ["45", "54", "44", "40"], answer: 1 },
            { question: "Hangisi en küçük sayıdır?", options: ["23", "32", "13", "31"], answer: 2 },
            { question: "Bir düzinede kaç tane vardır?", options: ["10", "11", "12", "13"], answer: 2 },
            { question: "Bir saatte kaç dakika vardır?", options: ["50", "60", "70", "100"], answer: 1 },
            { question: "Bir dakikada kaç saniye vardır?", options: ["50", "60", "70", "80"], answer: 1 },
            { question: "Yarım saat kaç dakikadır?", options: ["15", "20", "30", "45"], answer: 2 },
            { question: "Bir hafta kaç gündür?", options: ["5", "6", "7", "8"], answer: 2 },
            { question: "Karenin kaç kenarı vardır?", options: ["3", "4", "5", "6"], answer: 1 },
            { question: "Dairenin kaç kenarı vardır?", options: ["0", "1", "2", "4"], answer: 0 },
            { question: "Dikdörtgenin kaç köşesi vardır?", options: ["3", "4", "5", "6"], answer: 1 },
            { question: "7 x 0 kaçtır?", options: ["0", "1", "7", "70"], answer: 0 },
            { question: "9 x 1 kaçtır?", options: ["0", "1", "9", "10"], answer: 2 },
            { question: "25 + 25 kaçtır?", options: ["40", "45", "50", "55"], answer: 2 },
            { question: "100 - 45 kaçtır?", options: ["45", "50", "55", "65"], answer: 2 },
            { question: "3 basamaklı en küçük sayı hangisidir?", options: ["99", "100", "101", "199"], answer: 1 },
            { question: "2 basamaklı en büyük sayı hangisidir?", options: ["98", "99", "100", "89"], answer: 1 },
            { question: "6'nın yarısı kaçtır?", options: ["2", "3", "4", "5"], answer: 1 },
            { question: "18'in yarısı kaçtır?", options: ["8", "9", "10", "11"], answer: 1 },
            { question: "4 tane 5 lira kaç lira eder?", options: ["15", "20", "25", "30"], answer: 1 },
            { question: "Bir düzine yumurtanın yarısı kaç yumurtadır?", options: ["4", "5", "6", "7"], answer: 2 },
            { question: "45 sayısındaki onlar basamağı kaçtır?", options: ["4", "5", "9", "0"], answer: 0 },
            { question: "78 sayısındaki birler basamağı kaçtır?", options: ["7", "8", "0", "1"], answer: 1 },
            { question: "3 + 3 + 3 kaçtır?", options: ["6", "9", "12", "15"], answer: 1 },
            { question: "İki basamaklı sayılarda en büyük basamak hangisidir?", options: ["Birler", "Onlar", "Yüzler", "Binler"], answer: 1 },
            { question: "60 dakika kaç saat eder?", options: ["1", "2", "3", "4"], answer: 0 },
            { question: "120 dakika kaç saat eder?", options: ["1", "2", "3", "4"], answer: 1 },
            { question: "3 üçgenin toplam kaç kenarı vardır?", options: ["6", "9", "12", "15"], answer: 1 },
            { question: "2 kare şeklin toplam kaç köşesi vardır?", options: ["4", "6", "8", "10"], answer: 2 },
            { question: "90'ın 10 eksiği kaçtır?", options: ["70", "80", "90", "100"], answer: 1 },
            { question: "55 + 45 kaçtır?", options: ["90", "95", "100", "105"], answer: 2 },
            { question: "7 x 8 kaçtır?", options: ["54", "56", "58", "64"], answer: 1 },
            { question: "9 x 7 kaçtır?", options: ["56", "63", "72", "81"], answer: 1 },
            { question: "144 ÷ 12 kaçtır?", options: ["10", "11", "12", "13"], answer: 2 },
            { question: "Bir düzine kalemin 3 katı kaç kalem eder?", options: ["24", "30", "36", "42"], answer: 2 },
            { question: "3/4'ün ondalık karşılığı nedir?", options: ["0,25", "0,5", "0,75", "0,8"], answer: 2 },
            { question: "250 + 175 kaçtır?", options: ["400", "415", "425", "450"], answer: 2 },
            { question: "500 - 235 kaçtır?", options: ["255", "265", "275", "285"], answer: 1 },
            { question: "6 basamaklı en küçük sayı hangisidir?", options: ["10000", "99999", "100000", "100001"], answer: 2 }
        ]
    },
    "turkce": {
        id: "turkce",
        title: "Türkçe",
        icon: "📚",
        questions: [
            { question: "Alfabemizde kaç harf vardır?", options: ["27", "28", "29", "30"], answer: 2 },
            { question: "'Güzel' kelimesinin zıt anlamlısı nedir?", options: ["İyi", "Çirkin", "Büyük", "Tatlı"], answer: 1 },
            { question: "'Elma' kelimesi kaç hecelidir?", options: ["1", "2", "3", "4"], answer: 1 },
            { question: "Hangi cümlenin sonuna soru işareti konur?", options: ["Bugün hava çok güzel", "Nereye gidiyorsun", "Kitap okumayı seviyorum", "Koşarak geldi"], answer: 1 },
            { question: "'Siyah' kelimesinin eş anlamlısı nedir?", options: ["Kara", "Ak", "Koyu", "Gece"], answer: 0 },
            { question: "'Büyük' kelimesinin zıt anlamlısı nedir?", options: ["Küçük", "Uzun", "Şişman", "Geniş"], answer: 0 },
            { question: "'Hızlı' kelimesinin zıt anlamlısı nedir?", options: ["Çabuk", "Yavaş", "Kısa", "Ağır"], answer: 1 },
            { question: "'Sıcak' kelimesinin zıt anlamlısı nedir?", options: ["Ilık", "Soğuk", "Ateşli", "Kaynar"], answer: 1 },
            { question: "'Aç' kelimesinin zıt anlamlısı nedir?", options: ["Tok", "Yorgun", "Mutlu", "Üzgün"], answer: 0 },
            { question: "'Kirli' kelimesinin zıt anlamlısı nedir?", options: ["Bulanık", "Temiz", "Karanlık", "Islak"], answer: 1 },
            { question: "'Mutlu' kelimesinin eş anlamlısı nedir?", options: ["Üzgün", "Sevinçli", "Kızgın", "Yorgun"], answer: 1 },
            { question: "'Akıllı' kelimesinin eş anlamlısı nedir?", options: ["Zeki", "Aptal", "Yavaş", "Tembel"], answer: 0 },
            { question: "'Ev' kelimesinin eş anlamlısı nedir?", options: ["Konut", "Bahçe", "Sokak", "Okul"], answer: 0 },
            { question: "'İnce' kelimesinin zıt anlamlısı nedir?", options: ["Kalın", "Uzun", "Kısa", "Dar"], answer: 0 },
            { question: "'Kitap' kelimesi kaç hecelidir?", options: ["1", "2", "3", "4"], answer: 1 },
            { question: "'Okul' kelimesi kaç hecelidir?", options: ["1", "2", "3", "4"], answer: 1 },
            { question: "'Bilgisayar' kelimesi kaç hecelidir?", options: ["2", "3", "4", "5"], answer: 2 },
            { question: "'Kalem' kelimesi kaç hecelidir?", options: ["1", "2", "3", "4"], answer: 1 },
            { question: "'Merhaba' kelimesi kaç hecelidir?", options: ["2", "3", "4", "5"], answer: 1 },
            { question: "Hangi cümlenin sonunda ünlem işareti (!) kullanılır?", options: ["Bugün hava güzel", "Aman ne güzel bir gün!", "Nereye gidiyorsun", "Kitap okuyorum"], answer: 1 },
            { question: "Hangi cümlenin sonuna nokta konur?", options: ["Nereye gidiyorsun", "Ne kadar mutluyum", "Bugün okula gittim", "Aferin sana"], answer: 2 },
            { question: "Bir kişinin adı nasıl yazılır?", options: ["Küçük harfle", "Büyük harfle başlayarak", "Hiç yazılmaz", "Rakamla"], answer: 1 },
            { question: "Cümle sonuna hangi işaretlerden biri gelmez?", options: ["Nokta", "Soru işareti", "Ünlem işareti", "Virgül"], answer: 3 },
            { question: "'Kalem, defter ve silgi okul çantamdaydı.' cümlesinde kaç virgül kullanılmıştır?", options: ["0", "1", "2", "3"], answer: 1 },
            { question: "Türkçede kaç tane sesli (ünlü) harf vardır?", options: ["6", "7", "8", "9"], answer: 2 },
            { question: "Türkçede kaç tane sessiz (ünsüz) harf vardır?", options: ["19", "20", "21", "22"], answer: 2 },
            { question: "'Ali okula gitti.' cümlesinde kaç kelime vardır?", options: ["2", "3", "4", "5"], answer: 1 },
            { question: "İsim (ad) nedir?", options: ["Varlıkları adlandıran sözcük", "Hareket bildiren sözcük", "Sayı bildiren sözcük", "Soru bildiren sözcük"], answer: 0 },
            { question: "Fiil (eylem) nedir?", options: ["Varlık adı", "İş, oluş, hareket bildiren sözcük", "Renk bildiren sözcük", "Sayı bildiren sözcük"], answer: 1 },
            { question: "Hangisi bir isimdir (ad)?", options: ["Koşmak", "Masa", "Güzel", "Hızlıca"], answer: 1 },
            { question: "Hangisi bir fiildir (eylem)?", options: ["Kitap", "Kalem", "Koşmak", "Sandalye"], answer: 2 },
            { question: "'Kırmızı elma' tamlamasında hangi kelime sıfattır (niteler)?", options: ["Kırmızı", "Elma", "ve", "Hiçbiri"], answer: 0 },
            { question: "'Evler' kelimesinde kaç hece vardır?", options: ["1", "2", "3", "4"], answer: 1 },
            { question: "Hangi kelime 'ev' kelimesiyle kafiyelidir?", options: ["Kedi", "Sev", "Kitap", "Kalem"], answer: 1 },
            { question: "İki nokta (:) işareti ne zaman kullanılır?", options: ["Cümle bittiğinde", "Örnek verilecekken/açıklama yapılırken", "Soru sorulurken", "Şaşkınlık belirtilirken"], answer: 1 },
            { question: "'Kedi' kelimesinin ilk harfi hangisidir?", options: ["K", "E", "D", "İ"], answer: 0 },
            { question: "'Türkiye' kelimesinin kaç harfi vardır?", options: ["6", "7", "8", "9"], answer: 1 },
            { question: "Alfabede 'Ç' harfinden sonra hangi harf gelir?", options: ["B", "C", "D", "E"], answer: 2 },
            { question: "Alfabede 'A' harfinden sonra hangi harf gelir?", options: ["B", "C", "D", "E"], answer: 0 },
            { question: "Hangi kelime alfabetik sıraya göre ilk sırada yer alır?", options: ["Elma", "Armut", "Kiraz", "Muz"], answer: 1 },
            { question: "Bir öyküde (hikayede) olaylar genellikle nasıl sıralanır?", options: ["Karışık", "Giriş-gelişme-sonuç şeklinde", "Sondan başa", "Rastgele"], answer: 1 },
            { question: "Şiirlerde satır sonlarındaki ses benzerliğine ne denir?", options: ["Nokta", "Kafiye", "Virgül", "Ünlem"], answer: 1 },
            { question: "Masalların başında sıkça hangi söz kullanılır?", options: ["Bir varmış bir yokmuş", "Son", "Merhaba", "Teşekkürler"], answer: 0 },
            { question: "Bir mektuba başlarken en başa ne yazılır?", options: ["Konu", "Tarih ve hitap (Sevgili...)", "İmza", "Sonuç"], answer: 1 },
            { question: "'Konuşkan' kelimesinin zıt anlamlısı nedir?", options: ["Sessiz", "Gürültülü", "Neşeli", "Yorgun"], answer: 0 },
            { question: "'Cesur' kelimesinin zıt anlamlısı nedir?", options: ["Korkak", "Güçlü", "Akıllı", "Hızlı"], answer: 0 },
            { question: "'Yüksek' kelimesinin zıt anlamlısı nedir?", options: ["Geniş", "Alçak", "Uzun", "Dar"], answer: 1 },
            { question: "Bir paragrafta konunun anlatıldığı ilk cümleye ne denir?", options: ["Sonuç cümlesi", "Giriş cümlesi", "Ara cümle", "Başlık"], answer: 1 },
            { question: "'Biz yarın pikniğe gideceğiz.' cümlesi hangi zamandan bahseder?", options: ["Geçmiş zaman", "Şimdiki zaman", "Gelecek zaman", "Geniş zaman"], answer: 2 },
            { question: "'Dün okula gittim.' cümlesi hangi zamandan bahseder?", options: ["Geçmiş zaman", "Şimdiki zaman", "Gelecek zaman", "Geniş zaman"], answer: 0 },
            { question: "'Öğretmenimiz bize matematik dersini çok güzel anlattı.' cümlesinde kaç sözcük vardır?", options: ["6", "7", "8", "9"], answer: 1 },
            { question: "'Kitaplık' kelimesinin kökü nedir?", options: ["Kitaplık", "Kitap", "Lık", "Kit"], answer: 1 },
            { question: "Bir kelimenin anlamını taşıyan ve değişmeyen parçasına ne denir?", options: ["Hece", "Kök", "Ek", "Cümle"], answer: 1 },
            { question: "'Mavi gökyüzünde beyaz bulutlar süzülüyordu.' cümlesinde kaç sıfat vardır?", options: ["1", "2", "3", "4"], answer: 1 },
            { question: "Yüklemi cümle sonunda olan cümlelere ne denir?", options: ["Devrik cümle", "Kurallı cümle", "Eksiltili cümle", "Bağlı cümle"], answer: 1 },
            { question: "'geldiler' kelimesi kaç hecelidir?", options: ["2", "3", "4", "5"], answer: 1 },
            { question: "Hangi cümlede yazım yanlışı vardır?", options: ["Bu gün okula gittim.", "Bugün okula gittim.", "Yarın sinemaya gideceğim.", "Dün çok yorulmuştum."], answer: 0 },
            { question: "Anlamca birbirinin zıttı olan kelimelere ne denir?", options: ["Eş anlamlı", "Zıt anlamlı", "Sesteş", "Mecaz anlamlı"], answer: 1 }
        ]
    },
    "hayat-bilgisi": {
        id: "hayat-bilgisi",
        title: "Hayat Bilgisi",
        icon: "🌱",
        questions: [
            { question: "Karşıdan karşıya geçerken ilk nereye bakmalıyız?", options: ["Sağa", "Sola", "Yukarı", "Yere"], answer: 1 },
            { question: "Günde kaç kez dişlerimizi fırçalamalıyız?", options: ["Hiç", "1 kez", "En az 2 kez", "Sadece sabah"], answer: 2 },
            { question: "Hangisi sağlıklı bir yiyecektir?", options: ["Cips", "Şeker", "Elma", "Kola"], answer: 2 },
            { question: "Trafik lambasında 'Kırmızı' renk ne anlama gelir?", options: ["Geç", "Dur", "Hazırlan", "Koş"], answer: 1 },
            { question: "Hangisi kişisel bakımımızla ilgilidir?", options: ["Ödev yapmak", "Banyo yapmak", "Oyun oynamak", "Televizyon izlemek"], answer: 1 },
            { question: "Yangın durumunda hangi numara aranır?", options: ["155", "112", "110", "153"], answer: 2 },
            { question: "Polis imdat hangi numaradır?", options: ["110", "112", "155", "156"], answer: 2 },
            { question: "İtfaiye hangi numaradır?", options: ["110", "112", "155", "156"], answer: 0 },
            { question: "Trafik ışığında yeşil renk ne anlama gelir?", options: ["Dur", "Geç", "Hazırlan", "Bekle"], answer: 1 },
            { question: "Trafik ışığında sarı renk ne anlama gelir?", options: ["Dur", "Geç", "Hazırlan/Dikkat et", "Koş"], answer: 2 },
            { question: "Yayalar yolun neresinden karşıya geçmelidir?", options: ["İstediği yerden", "Yaya geçidinden", "Köşeden", "Ortadan"], answer: 1 },
            { question: "Okula giderken güvenlik için ne yapılmalıdır?", options: ["Koşarak geçilmeli", "Yaya geçidi kullanılmalı", "Gözler kapalı geçilmeli", "Telefonla oynanmalı"], answer: 1 },
            { question: "Hangisi temel ihtiyaçlarımızdan biridir?", options: ["Oyuncak", "Su", "Televizyon", "Bisiklet"], answer: 1 },
            { question: "Hangisi sağlıklı bir alışkanlıktır?", options: ["Düzenli uyumak", "Geç yatmak", "Sebze yememek", "Spor yapmamak"], answer: 0 },
            { question: "Ellerimizi ne zaman yıkamalıyız?", options: ["Sadece sabah", "Yemekten önce ve sonra", "Hiç yıkamayız", "Sadece uyumadan önce"], answer: 1 },
            { question: "Hangisi bir aile üyesi değildir?", options: ["Anne", "Baba", "Kardeş", "Komşu"], answer: 3 },
            { question: "Ailede büyüklere karşı nasıl davranmalıyız?", options: ["Saygılı", "Kaba", "İlgisiz", "Kayıtsız"], answer: 0 },
            { question: "Okulda arkadaşlarımızla nasıl davranmalıyız?", options: ["Kavga ederek", "Paylaşarak ve saygılı", "Bencilce", "İlgisizce"], answer: 1 },
            { question: "Çevremizi temiz tutmak için ne yapmalıyız?", options: ["Çöpü yere atmak", "Çöpü çöp kutusuna atmak", "Suyu israf etmek", "Ağaçları kesmek"], answer: 1 },
            { question: "Suyu tasarruflu kullanmak için ne yapmalıyız?", options: ["Musluğu açık bırakmak", "Kullanmadığımızda musluğu kapatmak", "Uzun süre duş almak", "Bahçeyi gereksiz sulamak"], answer: 1 },
            { question: "Elektriği tasarruflu kullanmak için ne yapmalıyız?", options: ["Kullanılmayan lambaları açık bırakmak", "Kullanılmayan lambaları söndürmek", "Tüm gün televizyon açık bırakmak", "Fark etmez"], answer: 1 },
            { question: "Geri dönüşüm nedir?", options: ["Çöpleri yakmak", "Atık maddeleri yeniden kullanılabilir hale getirmek", "Çöpleri denize atmak", "Hiçbir şey"], answer: 1 },
            { question: "Kağıt geri dönüşüm kutusunun rengi genellikle nedir?", options: ["Yeşil", "Mavi", "Kırmızı", "Sarı"], answer: 1 },
            { question: "Cam geri dönüşüm kutusunun rengi genellikle nedir?", options: ["Yeşil", "Mavi", "Kırmızı", "Sarı"], answer: 0 },
            { question: "Hangi meslek insanları hastalıklardan tedavi eder?", options: ["Öğretmen", "Doktor", "Şoför", "Aşçı"], answer: 1 },
            { question: "Hangi meslek bize ders öğretir?", options: ["Doktor", "Öğretmen", "Polis", "İtfaiyeci"], answer: 1 },
            { question: "Hangi meslek yangınları söndürür?", options: ["Polis", "Doktor", "İtfaiyeci", "Öğretmen"], answer: 2 },
            { question: "Hangi meslek trafik düzenini sağlar ve güvenliği korur?", options: ["Aşçı", "Polis", "Terzi", "Ressam"], answer: 1 },
            { question: "Bayrağımıza karşı nasıl davranmalıyız?", options: ["Saygısızca", "Saygıyla", "Umursamadan", "Kayıtsızca"], answer: 1 },
            { question: "Milli marşımızın adı nedir?", options: ["Onuncu Yıl Marşı", "İstiklal Marşı", "Gençlik Marşı", "Bayrak Marşı"], answer: 1 },
            { question: "Ders başlarken ve biterken öğretmenimize ne yaparız?", options: ["Bağırırız", "Selam veririz", "Kaçarız", "Hiçbir şey yapmayız"], answer: 1 },
            { question: "Sınıfta söz almak için ne yapmalıyız?", options: ["Bağırmalıyız", "Parmak kaldırmalıyız", "Ayağa fırlamalıyız", "Konuşmamalıyız"], answer: 1 },
            { question: "Hangisi bir doğal afettir?", options: ["Doğum günü", "Deprem", "Bayram", "Tatil"], answer: 1 },
            { question: "Deprem sırasında ne yapmalıyız?", options: ["Panik yapıp koşmalıyız", "Çök-Kapan-Tutun kuralını uygulamalıyız", "Asansöre binmeliyiz", "Pencereye koşmalıyız"], answer: 1 },
            { question: "Sağlıklı beslenmek için ne yapmalıyız?", options: ["Sadece şekerli yiyecek yemek", "Meyve ve sebze yemek", "Hiç su içmemek", "Hep hazır yiyecek yemek"], answer: 1 },
            { question: "Hangisi mevsime uygun bir giyim örneğidir?", options: ["Kışın mont giymek", "Yazın kalın mont giymek", "Kışın mayo giymek", "Hiçbiri"], answer: 0 },
            { question: "Bisiklete binerken güvenlik için ne takmalıyız?", options: ["Şapka", "Kask", "Atkı", "Eldiven"], answer: 1 },
            { question: "Elektrikli aletlerle oynamak güvenli midir?", options: ["Evet her zaman", "Hayır, tehlikelidir", "Sadece yetişkin izniyle her zaman güvenlidir", "Fark etmez"], answer: 1 },
            { question: "Tanımadığımız kişilerden gelen teklifleri kabul etmeli miyiz?", options: ["Evet her zaman", "Hayır, güvenilir değilse kabul etmemeliyiz", "Fark etmez", "Her zaman gitmeliyiz"], answer: 1 },
            { question: "Okul kurallarına neden uyarız?", options: ["Sadece cezalandırılmamak için", "Düzenli ve güvenli bir ortam için", "Hiçbir sebep yok", "Sadece öğretmen istediği için"], answer: 1 },
            { question: "Hangisi bir yardımlaşma davranışıdır?", options: ["Arkadaşının eşyasını almak", "Düşen arkadaşına yardım etmek", "Kavga etmek", "Alay etmek"], answer: 1 },
            { question: "Büyüklerimize nasıl hitap etmeliyiz?", options: ["Kaba biçimde", "Saygılı ifadelerle", "Bağırarak", "Görmezden gelerek"], answer: 1 },
            { question: "Toplu taşımada nasıl davranmalıyız?", options: ["Bağırarak", "Sırada bekleyerek ve sessizce", "İterek", "Kurallara uymayarak"], answer: 1 },
            { question: "Hangisi kişisel eşyalarımızdandır?", options: ["Okul sırası", "Diş fırçası", "Sınıf panosu", "Bahçe"], answer: 1 },
            { question: "Yemekten önce neden ellerimizi yıkarız?", options: ["Hastalanmamak için", "Eğlenmek için", "Vakit geçirmek için", "Hiçbir sebep yok"], answer: 0 },
            { question: "Hangisi bir çevre kirliliği örneğidir?", options: ["Ağaç dikmek", "Çöpleri sokağa atmak", "Geri dönüşüm yapmak", "Suyu tasarruflu kullanmak"], answer: 1 },
            { question: "Ormanların korunması neden önemlidir?", options: ["Hiçbir önemi yok", "Hava temizliği ve hayvanlara yaşam alanı sağladığı için", "Sadece odun için", "Sadece meyve için"], answer: 1 },
            { question: "Aile bireyleriyle vakit geçirmek neden önemlidir?", options: ["Önemli değildir", "Sevgi ve bağ oluşturur", "Sadece zaman kaybıdır", "Hiçbir faydası yoktur"], answer: 1 },
            { question: "Hangisi tehlikeli bir davranıştır?", options: ["Yola dikkatli bakarak geçmek", "Sokakta koşarak oynamak", "Kemer takmak", "Kurallara uymak"], answer: 1 },
            { question: "Araçta giderken ne takmalıyız?", options: ["Hiçbir şey", "Emniyet kemeri", "Şapka", "Atkı"], answer: 1 },
            { question: "Türkiye Cumhuriyeti'nin yönetim şekli nedir?", options: ["Krallık", "Cumhuriyet", "İmparatorluk", "Hanedanlık"], answer: 1 },
            { question: "Türkiye'nin yasama organı (kanun yapan organ) hangisidir?", options: ["Cumhurbaşkanlığı", "TBMM (Türkiye Büyük Millet Meclisi)", "Bakanlar Kurulu", "Yargıtay"], answer: 1 },
            { question: "Bir ülkenin para politikasını genellikle hangi kurum yönetir?", options: ["Merkez Bankası", "Belediye", "Okul", "Hastane"], answer: 0 },
            { question: "Doğal kaynakları bilinçsizce tüketmenin sonucu genellikle nedir?", options: ["Bolluk", "Kıtlık/tükenme", "Hiçbir etkisi olmaz", "Daha fazla üretim"], answer: 1 },
            { question: "Hangisi temel bir insan hakkıdır?", options: ["Eğitim hakkı", "Başkasına zarar verme hakkı", "Çöp atma hakkı", "Gürültü yapma hakkı"], answer: 0 },
            { question: "Bir kaza veya acil durumda hangi numara aranmalıdır?", options: ["Komşunun numarası", "112 Acil Çağrı Merkezi", "Arkadaşın numarası", "Kimse aranmaz"], answer: 1 },
            { question: "Bir toplumda kuralların olmaması neye yol açar?", options: ["Düzensizlik ve kargaşa", "Daha fazla mutluluk", "Hiçbir şeye", "Daha fazla özgürlük"], answer: 0 },
            { question: "Vergi vermenin temel amacı nedir?", options: ["Kamu hizmetlerini finanse etmek", "Zenginleri cezalandırmak", "Hiçbir amacı yok", "Sadece devleti zorlamak"], answer: 0 }
        ]
    },
    "ingilizce-kelime": {
        id: "ingilizce-kelime",
        title: "İngilizce Kelime",
        icon: "🇬🇧",
        questions: [
            { question: "'Apple' ne demektir?", options: ["Armut", "Muz", "Elma", "Kiraz"], answer: 2 },
            { question: "'Cat' ne demektir?", options: ["Kuş", "Kedi", "Köpek", "Fare"], answer: 1 },
            { question: "'Red' hangi renktir?", options: ["Mavi", "Yeşil", "Sarı", "Kırmızı"], answer: 3 },
            { question: "Hangisi 'Dog' kelimesinin anlamıdır?", options: ["Kedi", "Köpek", "İnek", "Koyun"], answer: 1 },
            { question: "'One' hangi sayıdır?", options: ["1", "2", "3", "4"], answer: 0 },
            { question: "'Banana' ne demektir?", options: ["Elma", "Muz", "Portakal", "Çilek"], answer: 1 },
            { question: "'Orange' ne demektir (meyve olarak)?", options: ["Elma", "Muz", "Portakal", "Üzüm"], answer: 2 },
            { question: "'Bird' ne demektir?", options: ["Balık", "Kuş", "Kedi", "At"], answer: 1 },
            { question: "'Fish' ne demektir?", options: ["Kuş", "Balık", "Yılan", "Kaplumbağa"], answer: 1 },
            { question: "'Horse' ne demektir?", options: ["İnek", "At", "Koyun", "Keçi"], answer: 1 },
            { question: "'Cow' ne demektir?", options: ["İnek", "At", "Domuz", "Koyun"], answer: 0 },
            { question: "'Blue' hangi renktir?", options: ["Kırmızı", "Sarı", "Mavi", "Yeşil"], answer: 2 },
            { question: "'Green' hangi renktir?", options: ["Yeşil", "Sarı", "Mor", "Turuncu"], answer: 0 },
            { question: "'Yellow' hangi renktir?", options: ["Sarı", "Mavi", "Kırmızı", "Siyah"], answer: 0 },
            { question: "'Black' hangi renktir?", options: ["Beyaz", "Siyah", "Gri", "Kahverengi"], answer: 1 },
            { question: "'White' hangi renktir?", options: ["Siyah", "Beyaz", "Gri", "Mavi"], answer: 1 },
            { question: "'Two' hangi sayıdır?", options: ["1", "2", "3", "4"], answer: 1 },
            { question: "'Three' hangi sayıdır?", options: ["2", "3", "4", "5"], answer: 1 },
            { question: "'Four' hangi sayıdır?", options: ["3", "4", "5", "6"], answer: 1 },
            { question: "'Five' hangi sayıdır?", options: ["4", "5", "6", "7"], answer: 1 },
            { question: "'Ten' hangi sayıdır?", options: ["8", "9", "10", "11"], answer: 2 },
            { question: "'Mother' ne demektir?", options: ["Baba", "Anne", "Kardeş", "Dede"], answer: 1 },
            { question: "'Father' ne demektir?", options: ["Anne", "Baba", "Kardeş", "Nine"], answer: 1 },
            { question: "'Sister' ne demektir?", options: ["Erkek kardeş", "Kız kardeş", "Anne", "Baba"], answer: 1 },
            { question: "'Brother' ne demektir?", options: ["Kız kardeş", "Erkek kardeş", "Anne", "Baba"], answer: 1 },
            { question: "'Book' ne demektir?", options: ["Kalem", "Kitap", "Defter", "Silgi"], answer: 1 },
            { question: "'Pen' ne demektir?", options: ["Kalem (tükenmez)", "Kitap", "Silgi", "Çanta"], answer: 0 },
            { question: "'Table' ne demektir?", options: ["Sandalye", "Masa", "Kapı", "Pencere"], answer: 1 },
            { question: "'Chair' ne demektir?", options: ["Masa", "Sandalye", "Kapı", "Pencere"], answer: 1 },
            { question: "'Door' ne demektir?", options: ["Pencere", "Kapı", "Duvar", "Çatı"], answer: 1 },
            { question: "'Window' ne demektir?", options: ["Kapı", "Pencere", "Duvar", "Çatı"], answer: 1 },
            { question: "'Sun' ne demektir?", options: ["Ay", "Güneş", "Yıldız", "Bulut"], answer: 1 },
            { question: "'Moon' ne demektir?", options: ["Güneş", "Ay", "Yıldız", "Gökyüzü"], answer: 1 },
            { question: "'Water' ne demektir?", options: ["Ateş", "Su", "Hava", "Toprak"], answer: 1 },
            { question: "'House' ne demektir?", options: ["Okul", "Ev", "Bahçe", "Sokak"], answer: 1 },
            { question: "'School' ne demektir?", options: ["Ev", "Okul", "Bahçe", "Park"], answer: 1 },
            { question: "'Friend' ne demektir?", options: ["Düşman", "Arkadaş", "Öğretmen", "Aile"], answer: 1 },
            { question: "'Happy' ne demektir?", options: ["Üzgün", "Mutlu", "Kızgın", "Yorgun"], answer: 1 },
            { question: "'Sad' ne demektir?", options: ["Mutlu", "Üzgün", "Kızgın", "Şaşkın"], answer: 1 },
            { question: "'Big' ne demektir?", options: ["Küçük", "Büyük", "Uzun", "Kısa"], answer: 1 },
            { question: "'Small' ne demektir?", options: ["Büyük", "Küçük", "Uzun", "Geniş"], answer: 1 },
            { question: "'Hot' ne demektir?", options: ["Soğuk", "Sıcak", "Ilık", "Serin"], answer: 1 },
            { question: "'Cold' ne demektir?", options: ["Sıcak", "Soğuk", "Ilık", "Kuru"], answer: 1 },
            { question: "'Eye' ne demektir?", options: ["Kulak", "Göz", "Burun", "Ağız"], answer: 1 },
            { question: "'Hand' ne demektir?", options: ["Ayak", "El", "Kol", "Parmak"], answer: 1 },
            { question: "'Head' ne demektir?", options: ["Baş/Kafa", "El", "Ayak", "Kol"], answer: 0 },
            { question: "'Foot' ne demektir?", options: ["El", "Ayak", "Baş", "Kol"], answer: 1 },
            { question: "'Monday' hangi gündür?", options: ["Salı", "Pazartesi", "Çarşamba", "Perşembe"], answer: 1 },
            { question: "'Sunday' hangi gündür?", options: ["Cumartesi", "Pazar", "Cuma", "Pazartesi"], answer: 1 },
            { question: "'Milk' ne demektir?", options: ["Su", "Süt", "Çay", "Kahve"], answer: 1 },
            { question: "'Yesterday' ne demektir?", options: ["Bugün", "Dün", "Yarın", "Şimdi"], answer: 1 },
            { question: "'Tomorrow' ne demektir?", options: ["Dün", "Bugün", "Yarın", "Geçen hafta"], answer: 2 },
            { question: "'Always' ne demektir?", options: ["Bazen", "Asla", "Her zaman", "Nadiren"], answer: 2 },
            { question: "'Between' ne demektir?", options: ["Üzerinde", "Altında", "Arasında", "Yanında"], answer: 2 },
            { question: "'Kitchen' ne demektir?", options: ["Yatak odası", "Mutfak", "Banyo", "Oturma odası"], answer: 1 },
            { question: "'Doctor' ne demektir?", options: ["Öğretmen", "Doktor", "Polis", "Aşçı"], answer: 1 },
            { question: "'Twenty' hangi sayıdır?", options: ["12", "20", "22", "25"], answer: 1 },
            { question: "'Because' ne demektir?", options: ["Ve", "Ama", "Çünkü", "Veya"], answer: 2 }
        ]
    },
    "bilim-doga": {
        id: "bilim-doga",
        title: "Bilim ve Doğa",
        icon: "🔬",
        questions: [
            { question: "Bitkiler güneş ışığıyla kendi besinlerini nasıl üretir?", options: ["Solunum", "Fotosentez", "Sindirim", "Dolaşım"], answer: 1 },
            { question: "Suyun katı haline ne denir?", options: ["Buhar", "Buz", "Sıvı", "Gaz"], answer: 1 },
            { question: "Suyun gaz haline ne denir?", options: ["Buz", "Kar", "Buhar", "Sis"], answer: 2 },
            { question: "Mıknatıs hangi metali çeker?", options: ["Altın", "Demir", "Bakır", "Alüminyum"], answer: 1 },
            { question: "Gökyüzünün mavi görünmesinin sebebi nedir?", options: ["Ay ışığı", "Güneş ışığının atmosferde saçılması", "Bulutlar", "Yıldızlar"], answer: 1 },
            { question: "İnsan vücudundaki en büyük organ hangisidir?", options: ["Kalp", "Beyin", "Deri", "Karaciğer"], answer: 2 },
            { question: "Hangisi bir enerji kaynağıdır?", options: ["Taş", "Güneş", "Kağıt", "Cam"], answer: 1 },
            { question: "Rüzgar neyin hareketiyle oluşur?", options: ["Suyun", "Havanın", "Toprağın", "Ateşin"], answer: 1 },
            { question: "Bitkilerin suyu topraktan almasını sağlayan kısmı hangisidir?", options: ["Yaprak", "Çiçek", "Kök", "Gövde"], answer: 2 },
            { question: "Bitkilerin nefes almasını sağlayan kısmı hangisidir?", options: ["Kök", "Yaprak", "Gövde", "Tohum"], answer: 1 },
            { question: "Hangisi bir gök cismidir?", options: ["Bulut", "Yıldız", "Kuş", "Uçak"], answer: 1 },
            { question: "Dünyamızın en yakın gezegeni hangisidir?", options: ["Mars", "Venüs", "Jüpiter", "Satürn"], answer: 1 },
            { question: "Kelebekler yumurtadan çıktıktan sonra önce neye dönüşür?", options: ["Tırtıl", "Kurbağa", "Karınca", "Kuş"], answer: 0 },
            { question: "Arılar çiçeklerden topladıkları maddeyle neyi üretir?", options: ["Süt", "Bal", "Yağ", "Şurup"], answer: 1 },
            { question: "Hangisi bir yenilenebilir enerji kaynağıdır?", options: ["Kömür", "Petrol", "Rüzgar", "Doğalgaz"], answer: 2 },
            { question: "Balıklar suyun içinde nasıl nefes alır?", options: ["Akciğerle", "Solungaçla", "Burunla", "Ağızla"], answer: 1 },
            { question: "Kuşların vücudunu hangisi kaplar?", options: ["Kürk", "Pul", "Tüy", "Deri"], answer: 2 },
            { question: "Balıkların vücudunu hangisi kaplar?", options: ["Tüy", "Kürk", "Pul", "Yün"], answer: 2 },
            { question: "Memelilerin vücudunu genellikle hangisi kaplar?", options: ["Pul", "Kürk/Kıl", "Tüy", "Kabuk"], answer: 1 },
            { question: "Hangi mevsimde ağaçların yaprakları dökülür?", options: ["İlkbahar", "Yaz", "Sonbahar", "Kış"], answer: 2 },
            { question: "Hangi mevsimde çiçekler açar ve doğa canlanır?", options: ["İlkbahar", "Yaz", "Sonbahar", "Kış"], answer: 0 },
            { question: "Termometre neyi ölçer?", options: ["Ağırlığı", "Sıcaklığı", "Uzunluğu", "Hızı"], answer: 1 },
            { question: "Bir cismin ağırlığını ne ile ölçeriz?", options: ["Cetvel", "Termometre", "Terazi", "Saat"], answer: 2 },
            { question: "Bir uzunluğu ne ile ölçeriz?", options: ["Terazi", "Cetvel", "Termometre", "Barometre"], answer: 1 },
            { question: "Gölgemiz en kısa ne zaman olur?", options: ["Sabah", "Öğlen (güneş tepedeyken)", "Akşam", "Gece"], answer: 1 },
            { question: "Hangisi bir katı maddedir?", options: ["Su", "Hava", "Taş", "Buhar"], answer: 2 },
            { question: "Hangisi bir sıvı maddedir?", options: ["Taş", "Süt", "Tahta", "Demir"], answer: 1 },
            { question: "Hangisi bir gaz maddedir?", options: ["Hava", "Taş", "Su", "Buz"], answer: 0 },
            { question: "Ay ışığı aslında nereden gelir?", options: ["Ay kendi ışığını üretir", "Güneş ışığının yansımasıdır", "Yıldızlardan gelir", "Dünya'dan gelir"], answer: 1 },
            { question: "Depremi ölçen alete ne denir?", options: ["Termometre", "Barometre", "Sismograf", "Pusula"], answer: 2 },
            { question: "Pusula bize neyi gösterir?", options: ["Saati", "Sıcaklığı", "Yönü", "Ağırlığı"], answer: 2 },
            { question: "Ormanlarda oksijeni asıl kim üretir?", options: ["Hayvanlar", "Ağaçlar/bitkiler", "Taşlar", "Sular"], answer: 1 },
            { question: "Suyun kimyasal formülü nedir?", options: ["CO2", "H2O", "O2", "NaCl"], answer: 1 },
            { question: "İnsan vücudundaki en büyük iç organ hangisidir?", options: ["Böbrek", "Karaciğer", "Mide", "Akciğer"], answer: 1 },
            { question: "Bitkilerin fotosentez yapabilmesi için hangi gaz gereklidir?", options: ["Oksijen", "Karbondioksit", "Azot", "Hidrojen"], answer: 1 },
            { question: "Ay'ın Dünya çevresindeki hareketine ne denir?", options: ["Dönme", "Dolanma (yörünge hareketi)", "Sapma", "Titreşim"], answer: 1 },
            { question: "Hangisi elektriği iletmeyen (yalıtkan) bir maddedir?", options: ["Bakır", "Demir", "Lastik", "Alüminyum"], answer: 2 },
            { question: "Ses, havasız ortamda (boşlukta) yayılabilir mi?", options: ["Yayılır", "Yayılmaz, çünkü ortam gerekir", "Daha hızlı yayılır", "Sadece gece yayılır"], answer: 1 },
            { question: "Bir mıknatısın kaç kutbu vardır?", options: ["1", "2", "3", "4"], answer: 1 },
            { question: "Dünya'nın kendi ekseni etrafında bir tur dönmesi ne kadar sürer?", options: ["1 saat", "24 saat", "1 hafta", "1 ay"], answer: 1 }
        ]
    }
};